# This is a basic workflow to help you get started with Actions

name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.1.0

    - name: Login to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: aliyun1983734399
        password: zsz100715!
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/homeassistant/home-assistant:2024.7.0.dev202406130219 docker://registry.cn-hangzhou.aliyuncs.com/github91/homeassistant/home-assistant:2024.7.0.dev202406130219
  
